image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE: "$CI_REGISTRY_IMAGE"

stages:
  - test
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
  script:
    - poetry run pytest --cov
    - poetry run ruff check .
  only:
    - merge_requests
    - main

build:
  stage: build
  script:
    - docker build -t "$IMAGE:$CI_COMMIT_SHA" .
    - docker push "$IMAGE:$CI_COMMIT_SHA"
    - docker tag "$IMAGE:$CI_COMMIT_SHA" "$IMAGE:latest"
    - docker push "$IMAGE:latest"
  only:
    - main
    - merge_requests
