version: '3.12'


services:
  db:
    restart: always
    image: postgres:16.3-alpine
    container_name: reddit_db
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  back:
    restart: always
    build: ./
    container_name: reddit_back
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume:
  media_volume:
