version: '3.12'


services:
  back:
    restart: always
    build: ./
    container_name: reddit_back
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
  db:
    restart: always
    image: postgres:16.3-alpine
    container_name: reddit_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  celery:
    build:
      context: .
    container_name: celery
    command: poetry run celery -A src.celery_app:celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env


volumes:
  postgres_data:
  static_volume:
  media_volume:
