# ruff.toml

# Какие директории и файлы проверять
include = ["src", "tests"]

# Исключить некоторые папки
exclude = [
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    "env",
]

# Целевая версия Python
target-version = "py312"  # Укажи здесь свою версию, например py310 или py39

# Макс длина строки (по стандарту PEP8 — 79, здесь сделаем 88 как в Black)
line-length = 88

# Какие правила активировать дополнительно
select = [
    "E",  # Pycodestyle errors
    "F",  # Pyflakes
    "B",  # Bugbear
    "I",  # isort (импорт-порядок)
]

# Можно отключить некоторые правила
ignore = [
    "E501",  # длинные строки (если ты форматируешь код автоформаттером как black)
]

# Автоисправление ошибок (если используешь ruff через команду fix)
fixable = ["ALL"]

# Не исправлять автоматически эти ошибки
unfixable = []

# Настройки сортировки импортов (аналог isort)
[isort]
known-first-party = ["reddit"]  # <-- здесь укажи название своей папки проекта
