"""status user model

Revision ID: 0642fd96dbcc
Revises: e8040f48fe2a
Create Date: 2025-04-11 23:33:23.248542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0642fd96dbcc'
down_revision: Union[str, None] = 'e8040f48fe2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'DELETED', name='userstatus'), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
