"""add resend cooldown

Revision ID: 0ef4427041e0
Revises: a491350f3509
Create Date: 2025-05-18 16:31:39.990728

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ef4427041e0"
down_revision: Union[str, None] = "a491350f3509"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("resend_cooldown", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "resend_cooldown")
    # ### end Alembic commands ###
