"""added row parrent_comment_id

Revision ID: 2d8aa00e710c
Revises: c0c378002400
Create Date: 2025-06-04 14:43:36.209986

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d8aa00e710c"
down_revision: Union[str, None] = "c0c378002400"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("parent_comment_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_comments_parent_comment_id"),
        "comments",
        ["parent_comment_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "comments", "comments", ["parent_comment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_index(op.f("ix_comments_parent_comment_id"), table_name="comments")
    op.drop_column("comments", "parent_comment_id")
    # ### end Alembic commands ###
