"""vote model added comment key

Revision ID: 38c626de86b3
Revises: e59ca6c30bc6
Create Date: 2025-04-02 12:57:15.105742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c626de86b3'
down_revision: Union[str, None] = 'e59ca6c30bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('votes', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_votes_comment_id'), 'votes', ['comment_id'], unique=False)
    op.create_foreign_key(None, 'votes', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_index(op.f('ix_votes_comment_id'), table_name='votes')
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('votes', 'comment_id')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
