"""added cascade to foreign keys in post models

Revision ID: 6e410cd77da1
Revises: 9e041dd42dd2
Create Date: 2025-03-27 18:56:20.743336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e410cd77da1'
down_revision: Union[str, None] = '9e041dd42dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_subreddit_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'subreddits', ['subreddit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subreddits', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subreddits', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_subreddit_id_fkey', 'posts', 'subreddits', ['subreddit_id'], ['id'])
    # ### end Alembic commands ###
