"""subscribers model upgrade

Revision ID: 8ea8d65436b8
Revises: bd3731a33a6f
Create Date: 2025-04-05 19:10:34.470658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea8d65436b8'
down_revision: Union[str, None] = 'bd3731a33a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_id_subreddit_id', 'subscriptions', ['user_id', 'subreddit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_id_subreddit_id', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
