"""comments_count row added to post model

Revision ID: 9e893e09ffbb
Revises: f638c8cd357a
Create Date: 2025-06-15 17:57:35.210783

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e893e09ffbb"
down_revision: Union[str, None] = "f638c8cd357a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("comments_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "comments_count")
    # ### end Alembic commands ###
