"""index added

Revision ID: a491350f3509
Revises: 0642fd96dbcc
Create Date: 2025-05-04 16:29:18.975431

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a491350f3509'
down_revision: Union[str, None] = '0642fd96dbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_sociallinks_url'), 'sociallinks', ['url'], unique=False)
    op.create_index(op.f('ix_sociallinks_user_id'), 'sociallinks', ['user_id'], unique=False)
    op.drop_constraint('subreddits_name_key', 'subreddits', type_='unique')
    op.create_index(op.f('ix_subreddits_name'), 'subreddits', ['name'], unique=True)
    op.create_index(op.f('ix_subscriptions_subreddit_id'), 'subscriptions', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_votes_comment_id'), 'votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_votes_post_id'), 'votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_post_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_comment_id'), table_name='votes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subreddit_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subreddits_name'), table_name='subreddits')
    op.create_unique_constraint('subreddits_name_key', 'subreddits', ['name'])
    op.drop_index(op.f('ix_sociallinks_user_id'), table_name='sociallinks')
    op.drop_index(op.f('ix_sociallinks_url'), table_name='sociallinks')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    # ### end Alembic commands ###
