"""subscribers model addded

Revision ID: bd3731a33a6f
Revises: 38c626de86b3
Create Date: 2025-04-05 17:35:32.373283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3731a33a6f'
down_revision: Union[str, None] = '38c626de86b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subreddits', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subreddits_created_by_id'), 'subreddits', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'subreddits', 'users', ['created_by_id'], ['id'])
    op.drop_index('ix_votes_comment_id', table_name='votes')
    op.drop_index('ix_votes_id', table_name='votes')
    op.drop_index('ix_votes_post_id', table_name='votes')
    op.drop_index('ix_votes_user_id', table_name='votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    op.create_index('ix_votes_post_id', 'votes', ['post_id'], unique=False)
    op.create_index('ix_votes_id', 'votes', ['id'], unique=False)
    op.create_index('ix_votes_comment_id', 'votes', ['comment_id'], unique=False)
    op.drop_constraint(None, 'subreddits', type_='foreignkey')
    op.drop_index(op.f('ix_subreddits_created_by_id'), table_name='subreddits')
    op.drop_column('subreddits', 'created_by_id')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
