"""index add to created_at and updated_At

Revision ID: c0c378002400
Revises: dd989a833f33
Create Date: 2025-05-28 18:06:01.605585

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0c378002400"
down_revision: Union[str, None] = "dd989a833f33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_comments_created_at"), "comments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_comments_updated_at"), "comments", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False)
    op.create_index(op.f("ix_posts_updated_at"), "posts", ["updated_at"], unique=False)
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_index(op.f("ix_roles_updated_at"), "roles", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_sociallinks_created_at"), "sociallinks", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sociallinks_updated_at"), "sociallinks", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_subreddits_created_at"), "subreddits", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_subreddits_updated_at"), "subreddits", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_created_at"),
        "subscriptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_updated_at"),
        "subscriptions",
        ["updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_votes_created_at"), "votes", ["created_at"], unique=False)
    op.create_index(op.f("ix_votes_updated_at"), "votes", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_updated_at"), table_name="votes")
    op.drop_index(op.f("ix_votes_created_at"), table_name="votes")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_subscriptions_updated_at"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_created_at"), table_name="subscriptions")
    op.drop_index(op.f("ix_subreddits_updated_at"), table_name="subreddits")
    op.drop_index(op.f("ix_subreddits_created_at"), table_name="subreddits")
    op.drop_index(op.f("ix_sociallinks_updated_at"), table_name="sociallinks")
    op.drop_index(op.f("ix_sociallinks_created_at"), table_name="sociallinks")
    op.drop_index(op.f("ix_roles_updated_at"), table_name="roles")
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_index(op.f("ix_posts_updated_at"), table_name="posts")
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    op.drop_index(op.f("ix_comments_updated_at"), table_name="comments")
    op.drop_index(op.f("ix_comments_created_at"), table_name="comments")
    # ### end Alembic commands ###
