"""subscribers count

Revision ID: f1dd7f272a20
Revises: 9e893e09ffbb
Create Date: 2025-06-25 17:18:29.511788

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1dd7f272a20"
down_revision: Union[str, None] = "9e893e09ffbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subreddits",
        sa.Column(
            "subscribers_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subreddits", "subscribers_count")
    # ### end Alembic commands ###
