"""added image row to post model

Revision ID: f638c8cd357a
Revises: 2d8aa00e710c
Create Date: 2025-06-15 15:09:13.401660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f638c8cd357a"
down_revision: Union[str, None] = "2d8aa00e710c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("image_path", sa.String(length=300), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "image_path")
    # ### end Alembic commands ###
